build.gradle
gradle.properties

This allows automated builds to grab the version easily
@sa-rrowcliffe @ldingSA

move version to properties

---

build.gradle
settings.gradle

@ldingSA @sa-rrowcliffe Can you ensure this doesnt break your local builds?
With this, our CI server can easily push to Artifactory.

add publishing config

---

src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/data/NumberProfile/CarrierInfo.java
src/main/java/org/secureauth/sarestapi/data/NumberProfile/CarrierStatus.java
src/main/java/org/secureauth/sarestapi/data/NumberProfile/CurrentCarrier.java
src/main/java/org/secureauth/sarestapi/data/NumberProfile/NumberProfileResult.java
src/main/java/org/secureauth/sarestapi/data/NumberProfile/OriginalCarrier.java
src/main/java/org/secureauth/sarestapi/data/Requests/NumberProfileRequest.java
src/main/java/org/secureauth/sarestapi/data/Requests/NumberProfileUpdateRequest.java
src/main/java/org/secureauth/sarestapi/data/Response/NumberProfileResponse.java
src/main/java/org/secureauth/sarestapi/interfaces/AdHocInterface.java
src/main/java/org/secureauth/sarestapi/interfaces/PhoneNumberProfileInterface.java
src/main/java/org/secureauth/sarestapi/queries/NumberProfileQuery.java
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java
src/main/java/org/secureauth/sarestapi/resources/s.java
src/test/java/org/secureauth/restapi/test/Impl/AdHocImpl.java
src/test/java/org/secureauth/restapi/test/Impl/PhoneNumberProfileImpl.java
src/test/java/org/secureauth/restapi/test/TestRestAPIInterfaces.java

Merging updates to support Phone Services from 9.0.2 along with ADHoc OTP delivery to SMS, Voice and Email

Updated SDk to support Phone Number Services from 9.0.2

---

src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java

Removed unused package import that caused build failure

Removed Unused Import causing build failure

---

gradle.properties
src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java

Reverted back to Seconds to get the SDK back to usable state in the public repo

Patched the Millisecond header

---

gradle.properties
src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java

Remove encoding and add raw json get request

---

gradle.properties
src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/data/Requests/PushToAcceptBiometricsRequest.java

*Description*: Support for push_accept_biometric

Biometric push to accept request support.

---

src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/data/Response/ResponseObject.java

Separate P2A methods + Added Symbol to response.

Separate P2A methods + Added Symbol to response.

---

src/test/java/org/secureauth/sarestapi/BaseResponseUtils.java
src/test/java/org/secureauth/sarestapi/SAAccessTest.java
src/test/resources/test.properties

JSI:6 copy radius diagnostic tools to sdk

JSI:6 copy radius diagnostic tools to sdk

---

gradle.properties
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java
src/main/java/org/secureauth/sarestapi/ssl/SATrustManagerFactory.java
src/test/java/org/secureauth/sarestapi/ssl/SATrustManagerFactoryTest.java
src/test/java/org/secureauth/sarestapi/ssl/X509CertificateMockedFactory.java
src/test/java/org/secureauth/sarestapi/util/RestApiHeaderTest.java

**Description** : Certificates validation when saBaseURL is not self signed

RAD-559: certificates validation when saBaseURL is not self signed

---

gradle.properties
src/main/java/org/secureauth/sarestapi/ISAAccess.java
src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/resources/Resource.java
src/test/java/org/secureauth/restapi/test/SAAccessTDD.java

- new endpoint for /api/v2/authenticated
- new api version 1.0.6.1

RAD-DataLake: notify authenticated service.

---

gradle.properties
src/main/java/org/secureauth/sarestapi/ISAAccess.java
src/main/java/org/secureauth/sarestapi/SAAccess.java
src/test/java/org/secureauth/restapi/test/SAAccessTDD.java

- Parameter mfa added to "notifyAuthenticated" service method.

JSI-19 : mfa parameter added. method renamed.

---

gradle.properties
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java

As api user i want to be able to configure the IdP timeout value to maximize success ratio of the requests.

JSI-24: set timeout added.

---

.gitignore
src/main/java/org/secureauth/sarestapi/ISAAccess.java

Add missing method signature for ISAAccess interface:
* Method signature which was added is: "updateUserQP"

Add missing method signature for ISAAccess interface

---

src/main/java/org/secureauth/sarestapi/ISAAccess.java
src/main/java/org/secureauth/sarestapi/SAAccess.java
src/main/java/org/secureauth/sarestapi/data/Requests/DeleteUserRequest.java
src/main/java/org/secureauth/sarestapi/resources/Resource.java
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java
src/test/java/org/secureauth/restapi/test/SAAccessTDD.java
src/test/java/org/secureauth/sarestapi/util/Property.java
src/test/resources/test.properties

Add support to delete user from a specify domain. 
```
/**
* <p>
* 	    Delete User
* </p>
* @param userId the UserID to delete
* @param domain
* @param deleteRelatedData
* @return {@link ResponseObject}
*/
BaseResponse deleteUser(String userId, String domain, Boolean deleteRelatedData);
```
Working snippet to access the method
```
ISAAccess saAccess = SAFactory.of(applianceHost, appliancePort, applianceSSL, selfSigned, realm, applicationID, applicationKey);
try {
BaseObject answer = saAccess.deleteUser(user, domain, Boolean.FALSE);
if ("success".equals( answer.getStatus())) {
System.out.println("Delete successfully");
} else {
System.out.println("Delete unsuccessfully");
}
}catch (SARestAPIException e){
//handle exception
}
```

JSI-4: Delete user

---

build.gradle
buildLocal.bat

In order to improve the local building process for the an "offline" environment, we need to add the ability to export a local version to the local maven repository in this project.

JSI-33: building support for local environment added.

---

src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java

**Description** : Fix for "NullPointerException is thrown when a timeout occurs contacting IdP"

JSI-40: close response stream when not null to avoid NullPointerExceptions

---

src/main/java/org/secureauth/sarestapi/data/Requests/UserPasswordRequest.java
src/main/java/org/secureauth/sarestapi/resources/SAExecuter.java

JSI-40: json serialization issue was fixed. ChangePasswordQP was fixed.

---

src/test/java/org/secureauth/restapi/test/SAAccessTDD.java

- Cleanup tests logging
- Parametrized common responses making them easier to maintain
- Fixed wrong inputs in certain tests

JSI-48: Review tests in SAAccssTDD

---

build.gradle
gradle.properties
src/main/java/org/secureauth/sarestapi/data/PreferredMFA.java
src/main/java/org/secureauth/sarestapi/data/Response/FactorsResponse.java

In this PR we are adding preferredMFA to the objects that are returned on a factors response.
We will be able to use this info to have an accurate remember last 2FA later on.

Rad-741: Fix factors response for latest IdP Release

---

gradle.properties
src/main/java/org/secureauth/sarestapi/data/PreferredMFA.java
src/main/java/org/secureauth/sarestapi/data/Response/BaseResponse.java
src/main/java/org/secureauth/sarestapi/data/Response/FactorsResponse.java

RAD-663: Implement Preferred MFA feature

RAD-663: Implement Preferred MFA feature
